# 設定藍牙顯示名稱
CONFIG_ZMK_KEYBOARD_NAME="MACROPAD_PRO"

# 強制啟動 BLE 功能
CONFIG_ZMK_BLE=y

# 強化發射功率（由預設 0dBm 提升至 +8dBm，大幅提升穿透力與穩定度）
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 停用 Passkey 數字驗證，強制採用 Just Works 免密碼配對
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# 啟用 ZMK 實驗性 BLE 連線優化（解決 Windows/macOS 藍牙握手逾時）
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# 允許配對多個主機裝置
CONFIG_BT_MAX_PAIRED=5
